 class MyException extends Exception
{
//default constructor generated by compiler
}
public class user_define_extra1
{
	public static void main(String []args)
	{
		try
		{
			throw new MyException();
		}
		catch(MyException e)
		{
			System.out.println(e.getMessage());
			System.out.println("Exception caught successfully");
		}
	}
}
